### ISSUE TITLE
It can not install on version 1.14.1

### ISSUE THREAD

**Issue by SoranKhezri** [gflujan/day-off-vsc-theme#1]
It can not install on version 1.14.1. and please a demo pic of your theme to see

![image](https://user-images.githubusercontent.com/43876320/72730258-41a28000-3ba6-11ea-94ae-78557972c658.png)

**Comment by gflujan** [comment]
I've reverted the VS Code engine version to be `^1.38.0`. Please update the extension/theme and let me know if that works.

Also, I noticed that your error image says that you have VS Code v1.41.0. I developed this theme on 1.41.1 and that's what the original engine version was set to.

![Installed](https://user-images.githubusercontent.com/26269014/72746929-3597cd80-3b68-11ea-9c18-b4e72ac2269f.png)
![VS Code Version](https://user-images.githubusercontent.com/26269014/72746931-3597cd80-3b68-11ea-9053-c2c02c6f7cab.png)

If updating the extension alone doesn't work, please try updating VS Code if possible. Thanks for trying it out and let me know if you need any additional help!

**Comment by SoranKhezri** [comment]
OK. I upgrade vs code and your theme installed very well. thanks
